import {equipment} from "./equipmentItemInterface";
import {workItemInterface} from "./workItemInterface";

import {activeTask} from "./activeTaskInterface";


export interface bunnyInterface{
    bunny:{
        id:number,
        name:string,
        vitality:number,
        crt:number,
        stamina:number,
        lvl:number,

        stats:{
            str:number,
            dex:number,
            vit:number,
            int:number,
            krm:number,
        },

        base:{
            rabbit:string,
            overhead?:string,
            mouth?:string,
            eyes?:string,
            bg?:string,
            faces?:string,
        },

        equipment:{
            rightHand?:{
                id:number,
                rarity:string,
                name:string,
                str:number,
                dex:number,
                vit:number,
                int:number,
                krm:number,
                requirements?:{
                    str?:number,
                    vit?:number,
                    int?:number,
                    krm?:number,
                    dex?:number,
                }
            },
            leftHand?:{
                id:number,
                rarity:string,
                name:string,
                str:number,
                dex:number,
                vit:number,
                int:number,
                krm:number,
                requirements?:{
                    str?:number,
                    vit?:number,
                    int?:number,
                    krm?:number,
                    dex?:number,
                }
            },
            hat?:{
                id:number,
                rarity:string,
                name:string,
                str:number,
                dex:number,
                vit:number,
                int:number,
                krm:number,
                requirements?:{
                    str?:number,
                    vit?:number,
                    int?:number,
                    krm?:number,
                    dex?:number,
                }
            },
            clothes?:{
                id:number,
                rarity:string,
                name:string,
                str:number,
                dex:number,
                vit:number,
                int:number,
                krm:number,
                requirements?:{
                    str?:number,
                    vit?:number,
                    int?:number,
                    krm?:number,
                    dex?:number,
                }
            },
            neck?:{
                id:number,
                rarity:string,
                name:string,
                str:number,
                dex:number,
                vit:number,
                int:number,
                krm:number,
                requirements?:{
                    str?:number,
                    vit?:number,
                    int?:number,
                    krm?:number,
                    dex?:number,
                }
            },
            hears?:{
                id:number,
                rarity:string,
                name:string,
                str:number,
                dex:number,
                vit:number,
                int:number,
                krm:number,
                requirements?:{
                    str?:number,
                    vit?:number,
                    int?:number,
                    krm?:number,
                    dex?:number,
                }
            },
        },
        isInventoryOpen:boolean,
        currentInventoryTab:string,
        inventory:{
            id:number,
            rarity:string,
            name:string,
            type:string,
            str:number,
            dex:number,
            vit:number,
            int:number,
            krm:number,
            requirements?:{
                str?:number,
                dex?:number,
                vit?:number,
                int?:number,
                krm?:number,
            }
        }[],

        work?:Array<activeTask>,

        activeTask?:activeTask,
    },


}
