export interface equipment{
        id:number,
        rarity:string
        name:string,
        type:string,
        miniature?:string
        str:number,
        dex:number,
        vit:number,
        int:number,
        krm:number,
        requirements?:{
                str?:number,
                dex?:number,
                vit?:number,
                int?:number,
                krm?:number,
        }
}